apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod
  namespace: vanilla
  labels:
    app: hello-world
spec:
  containers:
    - name: busybox-container
      image: busybox
      command: ["/bin/sh", "-c", "while true; do date; sleep 5; done"]
      resources:
        requests:
          memory: "1Gi"
          cpu: "1.5"
        limits:
          memory: "2Gi"
          cpu: "2"
  restartPolicy: Always
